---
- name: install open jdk 1.8
  yum:
    name: "{{ install_pkg }}"
    state: present

- name: create user "nexus" and its a /bin/nologin
  user:
    name: "{{ user_name }}"
    comment: "Nexus"
    shell: /bin/nologin
    state: present

- name: crete group nexus
  group:
    name: "{{ group_name }}"
    state: present

- name: Download nexus tar.gz file from internet
  get_url:
    url: "{{ nexus_url }}"
    dest: "/opt"
    mode: '0440'

- name: Unarchive nexus tar file that is already on the remote machine
  unarchive:
    src: "/opt/nexus-{{ nexus_version }}-unix.tar.gz"
    dest: "/opt"
    remote_src: yes

- name: Create a directory for installing nexus if it does not exist
  file:
    path: "/opt/sonatype-work"
    state: directory
    recurse: yes
    owner: "{{ user_name }}"
    group: "{{ group_name }}"

- name: Create a directory for installing nexus if it does not exist
  file:
    path: "/opt/nexus-{{ nexus_version }}-unix"
    state: directory
    recurse: yes
    owner: "{{ user_name }}"
    group: "{{ group_name }}"

- name: Update symlink for opt/nexus
  file:
    path: "/opt/nexus"
    src: "/opt/nexus-{{ nexus_version }}-unix"
    state: link
    owner: "{{ user_name }}"
    group: "{{ group_name }}"

- name: Setting nexus user
  lineinfile:
    path: "/opt/nexus/bin/nexus.rc"
    regexp: "#run_as_user="
    line: "run_as_user=\"nexus\""

- name: Create symlink to start nexus as Linux service
  file:
    path: "/etc/init.d/nexus"
    src: "/opt/nexus/bin/nexus"
    state: link
    owner: "{{ user_name }}"
    group: "{{ group_name }}"

- name: Start and enable nexus service
  service:
    name: nexus
    state: started
    enabled: yes

